# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

default: true

# Heading style
MD003:
  style: "atx"

# Unordered list style
MD004:
  style: "dash"

# List indentation
MD007:
  indent: 2

# Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false

# Multiple headings with the same content
MD024:
  allow_different_nesting: true

# Inline HTML
MD033:
  allowed_elements:
    - br
    - img
    - details
    - summary

# Bare URL
MD034: false

# First line in file should be a top level heading
MD041: false
