---
extends: default
ignore-from-file: .gitignore
rules:
  line-length:
    max: 120
    ignore: |
      .github/workflows/
  truthy:
    ignore: |
      .github/workflows/
  document-start:
    present: true
